version: 2
jobs:
  build:
    docker:
      - image: idubrov/rust-stm32:latest
    steps:
      - run: cargo install clippy
      - checkout
      - run: cargo build
      - run: cargo test
      - run: cargo clippy
